version: '3'

services:

  httpbin:
    image: 190066226418.dkr.ecr.us-east-1.amazonaws.com/vault/httpbin:${VERSION:-latest}
    build:
      context: .
      dockerfile: vgs.dockerfile
    ports:
      - '8000:8000'

  test:
    image: python:3.9.16-slim
    build:
      context: .
      dockerfile: vgs.tests.dockerfile